# -*- coding: utf-8 -*-
"""YATA_team.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWlJblIQ0WCQaB902Qsl7zVD_1qwSC__
"""

# --- Setup: clone repo and install dependencies ---
!rm -rf MUSC_violin
!git clone https://github.com/MTG/violin-transcription.git MUSC_violin -q

# Core deps used by the demo / pipeline
!pip install -q yt-dlp mir_eval pretty_midi unidecode librosa soundfile

import os, sys, subprocess, zipfile
from pathlib import Path

import torch
import pretty_midi
from unidecode import unidecode

sys.path.append("MUSC_violin")
from musc.model import PretrainedModel

# --- Load pretrained MUSC violin model ---
device = "cuda" if torch.cuda.is_available() else "cpu"
model = PretrainedModel(instrument="violin").to(device)

print("Device:", device)
print("Model loaded.")

from google.colab import files

# Directory to store uploads and outputs
uploads_dir = Path("/content/uploads")
uploads_dir.mkdir(parents=True, exist_ok=True)

print("Upload one or more .m4a files now...")
uploaded = files.upload()  # you can select multiple files

uploaded_paths = []
for name, data in uploaded.items():
    safe_name = unidecode(name)
    out_path = uploads_dir / safe_name
    with open(out_path, "wb") as f:
        f.write(data)
    uploaded_paths.append(out_path)

print("Uploaded files:")
for p in uploaded_paths:
    print(" -", p.name)

# Install torchcodec as it's a dependency for torchaudio.load used by the model
!pip install torchcodec

import inspect
import numpy as np
import pretty_midi

def convert_to_wav(in_path: Path) -> Path:
    """
    Convert input audio to 44.1kHz mono wav (what MUSC expects).
    """
    wav_path = in_path.with_suffix(".wav")
    cmd = [
        "ffmpeg", "-y",
        "-i", str(in_path),
        "-ac", "1",          # mono
        "-ar", "44100",      # 44.1kHz
        str(wav_path)
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return wav_path


def _normalize_to_pretty_midi(out):
    """Normalize different possible returns to a PrettyMIDI object."""
    if isinstance(out, pretty_midi.PrettyMIDI):
        return out
    if isinstance(out, dict) and "midi" in out:
        return out["midi"]
    if isinstance(out, (list, tuple)) and len(out) > 0 and isinstance(out[0], pretty_midi.PrettyMIDI):
        return out[0]
    raise TypeError(f"Unexpected transcription return type: {type(out)}")


def safe_transcribe_local(model, audio_path: str, batch_size=32, postprocessing="spotify"):
    """
    Try multiple local-file transcription entry points,
    ALWAYS passing audio_path positionally (first arg).
    """

    # Candidate methods in order of likelihood
    candidates = []

    if hasattr(model, "transcribe"):
        candidates.append(model.transcribe)

    if hasattr(model, "transcribe_file"):
        candidates.append(model.transcribe_file)

    # Some versions store a ViolinTranscriber at model.transcriber
    if hasattr(model, "transcriber") and hasattr(model.transcriber, "transcribe"):
        candidates.append(model.transcriber.transcribe)

    tried = []

    for fn in candidates:
        # Try a few call patterns (positional path first!)
        patterns = [
            lambda: fn(audio_path, batch_size=batch_size, postprocessing=postprocessing),
            lambda: fn(audio_path, batch_size=batch_size),
            lambda: fn(audio_path, postprocessing=postprocessing),
            lambda: fn(audio_path),
        ]

        for call in patterns:
            try:
                out = call()
                return _normalize_to_pretty_midi(out)
            except TypeError as e:
                tried.append((fn.__qualname__, str(e)))
            except Exception as e:
                # If it was a real runtime error (not signature), surface it
                raise

    # If nothing worked, print what we tried to help debug
    msg = "Could not find a working local transcription call.\nTried:\n"
    msg += "\n".join([f"{name} -> {err}" for name, err in tried])
    raise RuntimeError(msg)


midi_paths = []

for in_path in uploaded_paths:
    print(f"\nProcessing: {in_path.name}")

    # 1) Convert to wav (44.1kHz mono)
    wav_path = convert_to_wav(in_path)
    print("  Converted to:", wav_path.name)

    # 2) Transcribe (positional path)
    midi_obj = safe_transcribe_local(
        model,
        str(wav_path),
        batch_size=32,
        postprocessing="spotify"
    )

    # 3) Save MIDI with same basename
    mid_path = in_path.with_suffix(".mid")
    midi_obj.write(str(mid_path))
    midi_paths.append(mid_path)

    print("  Saved MIDI:", mid_path.name)

print("\nDone! MIDI files:")
for p in midi_paths:
    print(" -", p.name)

zip_path = Path("/content/violin_midis.zip")
with zipfile.ZipFile(zip_path, "w") as zf:
    for mp in midi_paths:
        zf.write(mp, arcname=mp.name)

print("Created:", zip_path.name)
files.download(str(zip_path))